"""add user_mapping for max mentions

Revision ID: b7eac8b24689
Revises: cbedaa48c0ce
Create Date: 2026-07-15 16:17:50.446176

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7eac8b24689"
down_revision: str | Sequence[str] | None = "cbedaa48c0ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("redmine_user_id", sa.Integer(), nullable=False),
        sa.Column("max_user_id", sa.Integer(), nullable=False),
        sa.Column("max_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "redmine_user_id", "max_user_id", name="uq_user_mapping_redmine_max"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_mapping")
    # ### end Alembic commands ###
