"""add notified_due_date to sent_notifications

Revision ID: cbedaa48c0ce
Revises: daf8eff117c4
Create Date: 2026-07-15 12:38:38.020870

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbedaa48c0ce"
down_revision: str | Sequence[str] | None = "daf8eff117c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sent_notifications", sa.Column("notified_due_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sent_notifications", "notified_due_date")
    # ### end Alembic commands ###
